import { Chess } from "@weshell/xiangqi.js";
import Redis from "ioredis";
import { NextResponse } from "next/server";
export const runtime="nodejs";
type Player={sid:string;name:string};type Color="r"|"b";
type Match={id:string;red:Player;black:Player;fen:string;turn:Color;turnDeadline:number;status:"active"|"finished";winner:Color|null;reason:"checkmate"|"timeout"|"resign"|"draw"|null;lastMove:{from:string;to:string;iccs:string}|null;createdAt:number;finishedAt?:number};
const Q="wme-game:match-queue",QL="wme-game:queue-lock",RK="wme-game:rankings",TTL=3600,QTTL=600,TURN=30000;
function redis(){return process.env.REDIS_URL?new Redis(process.env.REDIS_URL):null}
async function lock(r:Redis,k:string,t=5){for(let i=0;i<8;i++){if(await r.set(k,"1","EX",t,"NX")==="OK")return true;await new Promise(x=>setTimeout(x,60))}return false}
async function unlock(r:Redis,k:string){try{await r.del(k)}catch{}}
async function ranking(r:Redis,w:string|null,l:string|null,d:string[]=[]){const k="wme-game:ranking-lock";if(!await lock(r,k))return;try{const a=(await r.get<any[]>(RK))||[],m=new Map(a.map(x=>[x.name,x])),g=(s:string)=>{const n=s.trim()||"遊民";if(!m.has(n))m.set(n,{name:n,wins:0,losses:0,draws:0,games:0,score:0});return m.get(n)};if(w&&l){const x=g(w),y=g(l);x.wins++;x.games++;x.score+=3;y.losses++;y.games++}else d.forEach(n=>{const x=g(n);x.draws++;x.games++;x.score++});await r.set(RK,[...m.values()].sort((x,y)=>y.score-x.score||y.wins-x.wins||x.name.localeCompare(y.name)))}finally{await unlock(r,k)}}
async function expire(r:Redis,m:Match){if(m.status!=="active"||Date.now()<m.turnDeadline)return m;const w:Color=m.turn==="r"?"b":"r",wn=w==="r"?m.red.name:m.black.name,ln=w==="r"?m.black.name:m.red.name,d={...m,status:"finished" as const,winner:w,reason:"timeout" as const,finishedAt:Date.now()};await r.set("wme-game:match:"+m.id,d,{ex:TTL});await ranking(r,wn,ln);return d}
function out(m:Match,sid:string){const color=m.red.sid===sid?"r":m.black.sid===sid?"b":null;return{matchId:m.id,color,opponent:color==="r"?m.black.name:color==="b"?m.red.name:null,fen:m.fen,turn:m.turn,turnDeadline:m.turnDeadline,status:m.status,winner:m.winner,reason:m.reason,lastMove:m.lastMove,serverNow:Date.now()}}
function owns(m:Match,s:string){return m.red.sid===s||m.black.sid===s}
export async function POST(req:Request){const r=redis();if(!r)return NextResponse.json({error:"Cloud memory is not configured."},{status:503});const b=await req.json().catch(()=>({})),a=String(b.action||""),sid=String(b.sessionId||""),name=String(b.name||"遊民").trim()||"遊民";if(!sid||sid.length<12)return NextResponse.json({error:"Invalid session."},{status:400});
if(a==="join"){if(!await lock(r,QL))return NextResponse.json({error:"Matchmaking busy, please retry."},{status:503});try{const pk="wme-game:player:"+sid,cur=await r.get<string>(pk);if(cur&&cur!=="QUEUE"){const m=await r.get<Match>("wme-game:match:"+cur);if(m&&m.status==="active"&&owns(m,sid))return NextResponse.json(out(m,sid));await r.del(pk)}const raws=(await r.lrange<string>(Q,0,50))||[],now=Date.now(),q:any[]=[];for(const z of raws){try{const p=JSON.parse(String(z));if(p?.sid&&now-p.createdAt<QTTL*1000)q.push(p);else await r.lrem(Q,0,z)}catch{await r.lrem(Q,0,z)}}for(const p of q.filter(x=>x.sid===sid))await r.lrem(Q,0,JSON.stringify(p));await r.del(pk);const opp=q.find(x=>x.sid!==sid);if(!opp){await r.lpush(Q,JSON.stringify({sid,name,createdAt:now}));await r.set(pk,"QUEUE",{ex:QTTL});return NextResponse.json({status:"waiting",serverNow:now})}await r.lrem(Q,0,JSON.stringify(opp));const id=crypto.randomUUID().replaceAll("-","").slice(0,12),x=new Chess(),m:Match={id,red:{sid:opp.sid,name:opp.name||"遊民"},black:{sid,name},fen:x.fen(),turn:"r",turnDeadline:now+TURN,status:"active",winner:null,reason:null,lastMove:null,createdAt:now};await r.set("wme-game:match:"+id,m,{ex:TTL});await r.set("wme-game:player:"+opp.sid,id,{ex:TTL});await r.set(pk,id,{ex:TTL});return NextResponse.json(out(m,sid))}finally{await unlock(r,QL)}}
if(a==="move"||a==="resign"){const id=String(b.matchId||""),lk="wme-game:match-lock:"+id;if(!await lock(r,lk))return NextResponse.json({error:"Game is busy, retry."},{status:409});try{let m=await r.get<Match>("wme-game:match:"+id);if(!m||!owns(m,sid))return NextResponse.json({error:"Match not found."},{status:404});m=await expire(r,m);if(m.status==="finished")return NextResponse.json(out(m,sid));const c:Color=m.red.sid===sid?"r":"b";if(m.turn!==c)return NextResponse.json({error:"Not your turn."},{status:409});if(a==="resign"){const w:Color=c==="r"?"b":"r",d={...m,status:"finished" as const,winner:w,reason:"resign" as const,finishedAt:Date.now()};await r.set("wme-game:match:"+id,d,{ex:TTL});await ranking(r,w==="r"?m.red.name:m.black.name,w==="r"?m.black.name:m.red.name);return NextResponse.json(out(d,sid))}const x=new Chess(m.fen),from=String(b.from||""),to=String(b.to||""),mv=x.move({from,to});if(!mv)return NextResponse.json({error:"Invalid Xiangqi move."},{status:400});const over=x.isGameOver(),mate=x.isCheckmate(),d:any={...m,fen:x.fen(),turn:x.turn(),turnDeadline:Date.now()+TURN,lastMove:{from,to,iccs:mv.iccs}};if(over){d.status="finished";d.winner=mate?c:null;d.reason=mate?"checkmate":"draw";d.finishedAt=Date.now();if(mate)await ranking(r,c==="r"?m.red.name:m.black.name,c==="r"?m.black.name:m.red.name);else await ranking(r,null,null,[m.red.name,m.black.name])}await r.set("wme-game:match:"+id,d,{ex:TTL});return NextResponse.json(out(d,sid))}catch{return NextResponse.json({error:"Invalid Xiangqi move."},{status:400})}finally{await unlock(r,lk)}}
if(a==="leave"){const pk="wme-game:player:"+sid,cur=await r.get<string>(pk);if(cur==="QUEUE"){for(const z of (await r.lrange<string>(Q,0,100))||[]){try{if(JSON.parse(String(z))?.sid===sid)await r.lrem(Q,0,z)}catch{}}await r.del(pk)}return NextResponse.json({ok:true})}return NextResponse.json({error:"Unknown action."},{status:400})}
export async function GET(req:Request){const r=redis();if(!r)return NextResponse.json({error:"Cloud memory is not configured."},{status:503});const sid=new URL(req.url).searchParams.get("sessionId")||"";if(!sid)return NextResponse.json({error:"Missing session."},{status:400});const pk="wme-game:player:"+sid,cur=await r.get<string>(pk);if(!cur)return NextResponse.json({status:"idle"});if(cur==="QUEUE")return NextResponse.json({status:"waiting",serverNow:Date.now()});const lk="wme-game:match-lock:"+cur,got=await lock(r,lk,3);try{let m=await r.get<Match>("wme-game:match:"+cur);if(!m||!owns(m,sid)){await r.del(pk);return NextResponse.json({status:"idle"})}if(got)m=await expire(r,m);return NextResponse.json(out(m,sid))}finally{if(got)await unlock(r,lk)}}
