"use client";

import { useEffect, useMemo, useState } from "react";

type MatchState={status:"waiting"|"active"|"finished"|"idle";matchId?:string;color?:"r"|"b";opponent?:string|null;fen?:string;turn?:"r"|"b";turnDeadline?:number;winner?:"r"|"b"|null;reason?:"checkmate"|"timeout"|"resign"|"draw"|null;lastMove?:{from:string;to:string;iccs:string}|null;serverNow?:number};
type Ranking={name:string;wins:number;losses:number;draws:number;games:number;score:number};
const files=["a","b","c","d","e","f","g","h","i"];
const pieces:Record<string,string>={k:"將",a:"士",b:"象",n:"馬",r:"車",c:"炮",p:"卒",K:"帥",A:"仕",B:"相",N:"馬",R:"俥",C:"炮",P:"兵"};

function sid(){const k="wme-game-session";let x=localStorage.getItem(k);if(!x){x=crypto.randomUUID();localStorage.setItem(k,x)}return x}

export default function Home(){
 const[name,setName]=useState("遊民"),[sessionId,setSessionId]=useState(""),[state,setState]=useState<MatchState>({status:"idle"}),[selected,setSelected]=useState(""),[remaining,setRemaining]=useState(30),[offset,setOffset]=useState(0),[rankings,setRankings]=useState<Ranking[]>([]),[message,setMessage]=useState("正在連線至公園棋園…");
 useEffect(()=>setSessionId(sid()),[]);
 useEffect(()=>{const h=(e:MessageEvent)=>{if(e.origin!=="https://www.wongmingempire.com"||e.data?.type!=="WME_MEMBER")return;setName(String(e.data.username||"").trim()||"遊民")};window.addEventListener("message",h);window.parent?.postMessage({type:"WME_GAME_READY"},"https://www.wongmingempire.com");return()=>window.removeEventListener("message",h)},[]);
 function sync(x:MatchState){setState(x);setMessage(x.status==="waiting"?"正在公園裡尋找對手…":x.status==="active"?(x.color===x.turn?"輪到你落子":\`等待 \${x.opponent||"對手"} 落子\`):x.status==="finished"?finish(x):"準備進入棋園…");if(x.serverNow)setOffset(x.serverNow-Date.now())}
 async function join(){if(!sessionId)return;try{const r=await fetch("/api/matches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"join",sessionId,name}),cache:"no-store"}),x=await r.json();if(!r.ok)setMessage(x.error||"配對服務暫時忙碌");else sync(x)}catch{setMessage("無法連線至雲端棋園")}}
 useEffect(()=>{if(!sessionId)return;const t=setTimeout(join,700);return()=>clearTimeout(t)},[sessionId]);
 useEffect(()=>{if(!sessionId)return;const t=setInterval(async()=>{try{const r=await fetch("/api/matches?sessionId="+encodeURIComponent(sessionId),{cache:"no-store"});if(r.ok)sync(await r.json())}catch{}},900);return()=>clearInterval(t)},[sessionId]);
 useEffect(()=>{const t=setInterval(()=>{if(state.status==="active"&&state.turnDeadline&&state.turn===state.color)setRemaining(Math.max(0,Math.ceil((state.turnDeadline-(Date.now()+offset))/1000)));else if(state.status!=="active")setRemaining(30)},200);return()=>clearInterval(t)},[state.status,state.turn,state.color,state.turnDeadline,offset]);
 useEffect(()=>{const load=()=>fetch("/api/rankings",{cache:"no-store"}).then(r=>r.ok?r.json():[]).then(setRankings).catch(()=>{});load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 function finish(x:MatchState){if(x.reason==="draw")return"本局和棋";if(!x.winner)return"本局結束";if(x.winner===x.color)return x.reason==="timeout"?"對手超時，你獲勝":x.reason==="resign"?"對手認輸，你獲勝":"將死！你獲勝";return x.reason==="timeout"?"你超時，對手獲勝":x.reason==="resign"?"你認輸，對手獲勝":"你被將死"}
 async function move(from:string,to:string){if(state.status!=="active"||!state.matchId||state.color!==state.turn)return;setSelected("");try{const r=await fetch("/api/matches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"move",matchId:state.matchId,sessionId,from,to})}),x=await r.json();if(r.ok)sync(x);else setMessage(x.error||"此步無效")}catch{setMessage("網路暫時中斷，棋局會在重新連線後同步")}}
 async function resign(){if(!state.matchId)return;const r=await fetch("/api/matches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"resign",matchId:state.matchId,sessionId})});if(r.ok)sync(await r.json())}
 async function again(){setSelected("");setMessage("再次尋找對手…");fetch("/api/matches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"join",sessionId,name})}).then(r=>r.json()).then(sync).catch(()=>{})}
 useEffect(()=>{const leave=()=>{if(sessionId)navigator.sendBeacon("/api/matches",new Blob([JSON.stringify({action:"leave",sessionId})],{type:"application/json"}))};addEventListener("pagehide",leave);return()=>removeEventListener("pagehide",leave)},[sessionId]);
 const board=useMemo(()=>{if(!state.fen)return[];return state.fen.split(" ")[0].split("/").map(row=>{const a:string[]=[];for(const ch of row){if(/[1-9]/.test(ch))for(let i=0;i<Number(ch);i++)a.push("");else a.push(ch)}return a})},[state.fen]);
 const cells=useMemo(()=>{const rs=state.color==="b"?[9,8,7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7,8,9];const cs=state.color==="b"?[8,7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7,8];return rs.flatMap(ri=>cs.map(ci=>({ri,ci,sq:files[ci]+(9-ri)})))},[state.color]);
 function click(sq:string){if(state.status!=="active"||state.color!==state.turn)return;const idx=Number(sq.slice(1)),ci=files.indexOf(sq[0]);const ri=9-idx,p=board[ri]?.[ci];if(selected){if(selected===sq)return setSelected("");move(selected,sq);return}if(p&&((state.color==="r"&&p===p.toUpperCase())||(state.color==="b"&&p===p.toLowerCase())))setSelected(sq)}
 return <main className="park"><header><div><div className="eyebrow">WONGMING EMPIRE</div><h1>公園象棋</h1><p>黃名帝國線上棋園</p></div><div className="member"><span>論壇會員</span><strong>{name}</strong></div></header><section className="layout"><div className="game-card"><div className="game-top"><div><span className="dot red"/>紅方：{state.color==="r"?name:(state.opponent||"等待")}</div><div className={remaining<=5&&state.status==="active"&&state.turn===state.color?"timer danger":"timer"}>{state.status==="waiting"?"配對中":state.status==="active"?\`思考 \${remaining}s\`:"本局結束"}</div><div><span className="dot black"/>黑方：{state.color==="b"?name:(state.opponent||"等待")}</div></div>{state.status==="waiting"?<div className="waiting"><div className="bench">象</div><h2>公園棋桌正在等候對手</h2><p>{message}</p><div className="waiting-line"><span/>尋找另一位黃名帝國會員<span/></div></div>:state.fen?<div className="xiangqi-board">{cells.map(({ri,ci,sq})=>{const p=board[ri]?.[ci];const dark=(ri+ci)%2===1;const river=ri===4||ri===5;return <button key={sq} className={\`x-square \${dark?"dark":""} \${river?"river":""} \${selected===sq?"selected":""}\`} onClick={()=>click(sq)}>{p&&<span className={p===p.toUpperCase()?"red-piece":"black-piece"}>{pieces[p]}</span>}{ci===0&&<small>{9-ri}</small>}{ri===9&&<i>{files[ci]}</i>}{ri===4&&ci===4&&<em>楚河</em>}{ri===5&&ci===4&&<em>漢界</em>}</button>})}</div>:<div className="waiting"><div className="bench">象</div><h2>{message}</h2></div>}<div className="status">{message}</div>{state.status==="active"&&<button className="resign" onClick={resign}>認輸並結束本局</button>}{state.status==="finished"&&<div className="result"><strong>{finish(state)}</strong><button onClick={again}>再找一位對手</button></div>}<p className="rules">真正中國象棋 9×10 棋盤。每回合思考時間固定 30 秒，超時由伺服器判定；暱稱只能來自黃名帝國論壇會員，未取得名稱時顯示「遊民」。</p></div><aside><div className="side-card"><h2>公園排行榜</h2><p className="muted">雲端記憶・永久累積</p><div className="rank-head"><span>名次／棋手</span><span>積分</span></div>{rankings.length===0?<div className="empty">尚無完整對局紀錄</div>:rankings.slice(0,10).map((r,i)=><div className="rank-row" key={r.name}><b>{i+1}</b><span>{r.name}<small>{r.games} 局・{r.wins} 勝</small></span><strong>{r.score}</strong></div>)}</div><div className="side-card note"><h2>棋園規則</h2><p>兩名玩家各自在自己的瀏覽器開啟遊戲即可配對，棋步、回合與倒數由雲端保存。</p><p>勝 3 分、和 1 分、敗 0 分，排行榜長期記憶。</p></div></aside></section></main>
}
